-- MySQL Script generated by MySQL Workbench
-- Wed Mar 20 19:50:44 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pf_ods
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `pf_ods` ;

-- -----------------------------------------------------
-- Schema pf_ods
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pf_ods` DEFAULT CHARACTER SET utf8 ;
USE `pf_ods` ;

-- -----------------------------------------------------
-- Table `pf_ods`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`customers` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`customers` (
  `customerNumber` INT(11) NOT NULL,
  `customerName` VARCHAR(50) NULL DEFAULT NULL,
  `contactFirstName` VARCHAR(50) NULL DEFAULT NULL,
  `contactLastName` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(30) NULL DEFAULT NULL,
  `addressLine1` VARCHAR(50) NULL DEFAULT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `postalCode` VARCHAR(15) NULL DEFAULT NULL,
  `country` VARCHAR(50) NULL DEFAULT NULL,
  `salesRepEmployeeNumber` INT(11) NULL DEFAULT NULL,
  `creditLimit` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`office`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`office` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`office` (
  `officeCode` VARCHAR(10) NOT NULL,
  `city` VARCHAR(50) NULL DEFAULT NULL,
  `phone` VARCHAR(50) NULL DEFAULT NULL,
  `addressLine1` VARCHAR(50) NULL DEFAULT NULL,
  `addressLine2` VARCHAR(50) NULL DEFAULT NULL,
  `state` VARCHAR(50) NULL DEFAULT NULL,
  `postalCode` VARCHAR(15) NULL DEFAULT NULL,
  `territory` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`employees` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`employees` (
  `employeeNumber` INT(11) NOT NULL,
  `lastName` VARCHAR(50) NULL DEFAULT NULL,
  `firstName` VARCHAR(50) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `extension` VARCHAR(10) NULL DEFAULT NULL,
  `officeCode` VARCHAR(10) NULL DEFAULT '1',
  PRIMARY KEY (`employeeNumber`),
  INDEX `officeCodeFK_idx` (`officeCode` ASC) VISIBLE,
  CONSTRAINT `officeCodeFK`
    FOREIGN KEY (`officeCode`)
    REFERENCES `pf_ods`.`office` (`officeCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`product` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`product` (
  `productCode` VARCHAR(15) NOT NULL,
  `productName` VARCHAR(70) NULL DEFAULT NULL,
  `productScale` VARCHAR(10) NULL DEFAULT NULL,
  `productVendor` VARCHAR(50) NULL DEFAULT NULL,
  `productDescription` VARCHAR(500) NULL DEFAULT NULL,
  `productLine` VARCHAR(50) NULL DEFAULT NULL,
  `buyPrice` DECIMAL(10,2) NULL DEFAULT NULL,
  `MSRP` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`productCode`),
  INDEX `productLineFK_idx` (`productLine` ASC) VISIBLE,
  CONSTRAINT `productLineFK`
    FOREIGN KEY (`productLine`)
    REFERENCES `pf_ods`.`productline` (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`customercalls`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`customercalls` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`customercalls` (
  `employeeNumber` INT(11) NOT NULL,
  `customerNumber` INT(11) NOT NULL,
  `productCode` VARCHAR(15) NOT NULL,
  `text` TEXT NULL DEFAULT NULL,
  `date` DATETIME NULL DEFAULT NULL,
  INDEX `customerNumberFK_idx` (`customerNumber` ASC) VISIBLE,
  INDEX `employeeNumberFK_idx` (`employeeNumber` ASC) VISIBLE,
  INDEX `productCodeFK_idx` (`productCode` ASC) VISIBLE,
  CONSTRAINT `customerNumberCallFK`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `pf_ods`.`customers` (`customerNumber`),
  CONSTRAINT `employeeNumberFK`
    FOREIGN KEY (`employeeNumber`)
    REFERENCES `pf_ods`.`employees` (`employeeNumber`),
  CONSTRAINT `productCodeCallFK`
    FOREIGN KEY (`productCode`)
    REFERENCES `pf_ods`.`product` (`productCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`customerproducts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`customerproducts` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`customerproducts` (
  `customerNumber` INT(11) NOT NULL,
  `productCode` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`customerNumber`),
  INDEX `productNumberFK_idx` (`productCode` ASC) VISIBLE,
  CONSTRAINT `customerNumberProductsFK`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `pf_ods`.`customers` (`customerNumber`),
  CONSTRAINT `productCodeFK`
    FOREIGN KEY (`productCode`)
    REFERENCES `pf_ods`.`product` (`productCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`orders` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`orders` (
  `orderDate` DATE NOT NULL,
  `requiredDate` DATE NULL DEFAULT NULL,
  `shippedDate` DATE NULL DEFAULT NULL,
  `status` VARCHAR(15) NULL DEFAULT NULL,
  `comments` VARCHAR(500) NULL DEFAULT NULL,
  `customerNumber` INT(11) NULL DEFAULT NULL,
  `orderNumber` INT(11) NOT NULL,
  PRIMARY KEY (`orderNumber`),
  INDEX `customerNumberFK_idx` (`customerNumber` ASC) VISIBLE,
  CONSTRAINT `customerNumberOrderFK`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `pf_ods`.`customers` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`orderdetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`orderdetails` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`orderdetails` (
  `orderNumber` INT(11) NOT NULL,
  `productCode` VARCHAR(15) NOT NULL,
  `quantityOrdered` INT(11) NULL DEFAULT NULL,
  `priceEach` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`orderNumber`, `productCode`),
  INDEX `productCodeFK_idx` (`productCode` ASC) VISIBLE,
  CONSTRAINT `orderNumberFK`
    FOREIGN KEY (`orderNumber`)
    REFERENCES `pf_ods`.`orders` (`orderNumber`),
  CONSTRAINT `productCodeOrderFK`
    FOREIGN KEY (`productCode`)
    REFERENCES `pf_ods`.`product` (`productCode`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`payments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`payments` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`payments` (
  `customerNumber` INT(11) NOT NULL,
  `checkNumber` VARCHAR(50) NULL DEFAULT NULL,
  `paymentDate` DATE NULL DEFAULT NULL,
  `amount` DECIMAL(10,2) NULL DEFAULT NULL,
  INDEX `customerNumberPaymentFK` (`customerNumber` ASC) VISIBLE,
  CONSTRAINT `customerNumberPaymentFK`
    FOREIGN KEY (`customerNumber`)
    REFERENCES `pf_ods`.`customers` (`customerNumber`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pf_ods`.`productLine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pf_ods`.`productLine` ;

CREATE TABLE IF NOT EXISTS `pf_ods`.`productLine` (
  `productLine` VARCHAR(50) NOT NULL,
  `textDescription` VARCHAR(4000) NULL DEFAULT NULL,
  `htmlDescription` VARCHAR(4000) NULL DEFAULT NULL,
  `image` MEDIUMBLOB NULL DEFAULT NULL,
  PRIMARY KEY (`productLine`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
